### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by seanvree** [instagrim-dev/headphones.bundle#13]
Is this still under development?  Used to work, no longer!

**Comment by instagrim-dev** [comment]
Hey there, sorry for the delay.

I haven't touched the codebase or used kodi/plex in a few years. Depending on how 'broken' it is, I don't mind fixing it for you. Can you elaborate on what's broken and possibly attach a log?

**Comment by seanvree** [comment]
@willpharaoh 

I uninstalled and reinstalled, looks good now. 

THX
